### ISSUE TITLE
PCB order information

### ISSUE THREAD

**Issue by chandikasilva** [BCLab-UNM/Swarmathon-Robot#1]
Hi, we are from the Universtiy of Houston and due to the versatility of the Swarmie robots, we are looking to build a few more. The parts list from this repository has been very useful, however we are having troubles ordering the custom PCB. We would really appreciate if you could send us any files or information that could help us in ordering this component. Thank you.

**Comment by jjakenichol** [comment]
Hello,

It's great to hear you are looking at building more, I'm excited to hear about how it goes for you.  I have just added the files for our PCB, now renamed the Swarmie Control board (SCB).  You can find them here: https://github.com/BCLab-UNM/Swarmathon-Robot/tree/master/CAD-Files/PCB%20Files/SwarmieControlBoard

The Swarmie also requires another PCB, which we call the Servo Extension Board (SEB).  This board adds functionality for the gripper.  We are currently working on getting those files to upload onto github.

Thanks!

**Comment by jjakenichol** [comment]
Here is a link to the second PCB, the SEB: https://github.com/BCLab-UNM/Swarmathon-Robot/tree/master/CAD-Files/PCB%20Files/ServoExtentionBoard

**Comment by chandikasilva** [comment]
Thank you so much for uploading the files of the PCB and SEB onto your git hub repository, they are very helpful.  However, we were wondering who you ordered the PCB and SEB from or did you assemble them yourselves. Thank you.
