### ISSUE TITLE
Ordering information

### ISSUE THREAD

**Issue by chandikasilva** [BCLab-UNM/Swarmathon-Robot#2]
Thank you so much for uploading the files of the PCB and SEB onto your git hub repository, they are very helpful.  However, we were wondering who you ordered the PCB and SEB from or did you assemble it yourselves. Thank you.

**Comment by jjakenichol** [comment]
You're welcome! We had ours produced by a local shop in Albuquerque, ETS: http://etsnm.com/

I am not sure but you should be able to order from ETS as well.  It's probably easier for you to order from an electronics manufacturer near you, I get the sense that they are scattered all over the country.  Just send them both of the folders for each PCB, and they will have everything they need. 

 If you have any issues with ETS or with finding another, we'd be happy to help.

**Comment by chandikasilva** [comment]
Thank you so much for your help. This information has been very useful to us.
