### ISSUE TITLE
Drill files

### ISSUE THREAD

**Issue by chandikasilva** [BCLab-UNM/Swarmathon-Robot#3]
Hi, the Gerber files that you have posted here are very helpful. We are working currently with a company near us to fabricate the PCB and SEB boards. However they say that their website can only takes one drill file per board. Is it possible to merge all of the drill files for the PCB board and upload it as a .XLN file. And to also do the same thing for the SEB drill files.

**Comment by jjakenichol** [comment]
Good to hear you're making progress; @joekloepp is our resident electrical engineer who designed the two PCBs.

Joe, is this doable? If so, you can email the .XLN files to me and I'll upload them.

**Comment by jjakenichol** [comment]
Sorry @chandikasilva, it looks like this can't be done with the software we used to design the PCBs.  As I recommended in the other issue, you can use another supplier.  Perhaps it's easiest to use our supplier, ETS in Albuquerque.
