### ISSUE TITLE
Gerber files for SEB

### ISSUE THREAD

**Issue by chandikasilva** [BCLab-UNM/Swarmathon-Robot#4]
Hello, 

We are currently trying to reformat the files you posted here: <https://github.com/BCLab-UNM/Swarmathon-Robot/tree/master/CAD-Files/PCB%20Files/ServoExtentionBoard/SEB%20REV%20A/GERBER%20FILES> 

We are trying to reformat them to the formats listed here: <https://macrofab.com/help/creating-managing-ordering-pcbs/required-design-files/?_ga=1.178620068.1686766981.1485802524>. So that they can be used by Macrofab.com.

We are using gerbv to try to reformat the files but they seem to crash the application. I was contacting you to see if anyone else had brought up this issue or to check if the files have been corrupted in some way? There were no issues when we tried to reformat the gerber files for the PCB using gerbv.

**Comment by jjakenichol** [comment]
Thanks for bringing this up.  We don't know of anyone else attempting this or having this issue, but we are looking into it.  I'll try to get back to you early this week.

**Comment by jjakenichol** [comment]
We double checked the SEB files and they are openable and editable for us, so they don't seem to be corrupt.  You might try another vendor.  If you send the files to ETS, the supplier we use, they will surely be able to produce the boards and ship them to you.
